### PR TITLE
Fix error json and tests

### PR DESCRIPTION
**Pull request by cquilboss**
- Fix error internal error: package "encoding/json" without types
- Fix tests
- Upgrade go 1.16

### CODE REVIEW

**Comment by vanillaricewraps** [comment]
@cquilboss can you explain what's the issue we are trying to fix? This is a forked library so ideally we the least changes possible unless we are committed to maintaining it in which case I would have to test this on `watson` as well.

**Comment by cquilboss** [comment]
@vanillaricewraps do we pause the lint or do we try to rebase the fork?

**Comment by vanillaricewraps** [comment]
> @vanillaricewraps do we pause the lint or do we try to rebase the fork?

I don't think we ever used the linters here because we were never committed to maintain this repo so back to my original question: what is the bug that we are trying to fix? Ideally we don't make changes in this repo unless absolutely necessary but if there is a small change you need to make for it to work with listing-services then we can try to release a beta version so we can test it in watson.

**Comment by cquilboss** [comment]
@vanillaricewraps Basically it does not compile anymore. When I now use the library with go 1.18 we get the error: `error: package "encoding/json" without types` at compilation.

It's a fork from now an old version, since then the original package got updated. I simply used a chunk of the latest version to make it work again. 

Yes you should test it against watson as well before merging.
Anyhow, if it's too much work to keep the library up to date, no worries I currently use this fork until we get this package stable.

**Comment by vanillaricewraps** [comment]
Closing in favour of https://github.com/TripleMint/gqlgenc/pull/2

**Pull request closed without merging**
